# -*- coding: utf-8 -*-
"""Analise de Dados Checkpoint Nivel 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MscSzopZJ2rgUxzmKgSRP3ikzHDPVFG4
"""

import pandas as pd

df = pd.read_csv('/content/vendas.csv')

df

# NaN
nan_df = df[df[['valor_venda', 'quantidade']].isna().any(axis=1)]

# Duplicados
dup_df = df[df.duplicated(subset=['valor_venda', 'quantidade'])]

print("NaN:\n", nan_df)
print("\nDuplicados:\n", dup_df)

df = df.dropna(subset=['valor_venda', 'quantidade'])

df[['valor_venda', 'quantidade']].isna().sum()

df

faturamento_total = (df['valor_venda'] * df['quantidade']).sum()
faturamento_total

df['faturamento'] = df['valor_venda'] * df['quantidade']

df.head()

df[['valor_venda', 'quantidade']].isna().sum()

df['data_venda'] = pd.to_datetime(df['data_venda'])

df.groupby(df['data_venda'].dt.to_period('M'))['faturamento'].sum()

faturamento_categoria = df.groupby('categoria')['faturamento'].sum().sort_values(ascending=False)
faturamento_categoria

import matplotlib.pyplot as plt

df['data_venda'] = pd.to_datetime(df['data_venda'])
df['mes'] = df['data_venda'].dt.to_period('M')

faturamento_mes = df.groupby('mes')['faturamento'].sum()
faturamento_mes

faturamento_mes.index = faturamento_mes.index.astype(str)

plt.figure()
plt.plot(faturamento_mes.index, faturamento_mes.values)

plt.xlabel('Mês')
plt.ylabel('Faturamento')
plt.title('Faturamento Total por Mês')

plt.xticks(rotation=45)
plt.tight_layout()

plt.show()

plt.figure()
plt.bar(faturamento_categoria.index, faturamento_categoria.values)

plt.xlabel('Categoria')
plt.ylabel('Faturamento')
plt.title('Faturamento Total por Categoria')

plt.xticks(rotation=45)
plt.tight_layout()

plt.show()

